### ISSUE TITLE
REPORTE FINAL 

### ISSUE THREAD

**Issue by Anakimberly** [SistemasTecTlaxiaco/actividad-final-proyecto-final-equipo-j-a-k#1]
[Manipulacion de datos Reporte 3.pdf](https://github.com/SistemasTecTlaxiaco/actividad-final-proyecto-final-equipo-j-a-k/files/15458871/Manipulacion.de.datos.Reporte.3.pdf)

Reporte Actualizado con las nuevas funciones:
[REP.3 MANIPULACION DE DATOS.pdf](https://github.com/user-attachments/files/15517109/REP.3.MANIPULACION.DE.DATOS.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Calificacion 58
